CREATE TABLE `token`
(
    id        INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    token     VARCHAR(255) NOT NULL,
    isExpired BOOLEAN NOT NULL
);

ALTER TABLE `user` ADD COLUMN isVerified BOOLEAN NOT NULL DEFAULT FALSE;
